fix(windows): Remove freetype2 + another usage of cmake build on Windows (#987)
Like #985 , this fixes another failure blocking the windows build - freetype2 was also dependent on CMake.

Manifests as another windows build failure on Onivim nightly/master:
```
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: esy-freetype2@2.9.1007

    # esy-build-package: pwd: C:\Users\VssAdministrator\.esy\3\b\esy_freetype2-2.9.1007-dbc259b7

    # esy-build-package: running: "bash" "-c" "./esy/configure-windows.sh"

    INSTALL: /cygdrive/c/Users/VssAdministrator/.esy/3______________________________________________________/s/esy_freetype2-2.9.1007-dbc259b7
    error: command failed: "bash" "-c" "./esy/configure-windows.sh" (exited with 127)

    esy-build-package: exiting with errors above...

    
  building esy-freetype2@2.9.1007
esy: exiting due to errors above
```

We actually don't use freetype2 at all on Windows, anymore, as Skia uses DirectWrite API - so to unblock the builds, this picks up https://github.com/esy-packages/esy-freetype2 to remove this usage of cmake on Windows.